- name: install libasound 
  apt:
    name: 'libasound2-dev'
    state: present
    update-cache: yes
  become: true

- name: install alsaaudio lib for python
  pip:
    name: 'pyalsaaudio'
    state: present
  become: true
  become_user: pi

- name: Set volume for mic
  command: amixer sset Mic 16 -c 1

- name: clone clap-detector
  git:
    repo: 'https://github.com/mpsamurai/clap-detector.git'
    dest: /neochi/clap-detector
  become: true
  become_user: pi
  
- name: Create symlink to neochi-core
  file:
    src: "/neochi/neochi-core/src/neochi"
    dest: "/neochi/clap-detector/src/neochi"
    state: link
